// <auto-generated />
namespace HappyTrip.UI.MVC.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class abc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(abc));
        
        string IMigrationMetadata.Id
        {
            get { return "201410241627535_abc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
