// <auto-generated />
namespace HappyTrip.Data.EFRepository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class e : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(e));
        
        string IMigrationMetadata.Id
        {
            get { return "201411261316084_e"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
